---
- name: Install Apache
  package:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: present

- name: Start and enable Apache
  service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: true

- name: Deploy index.html
  template:
    src: templates/index.html.j2
    dest: "{{ '/var/www/html/index.html' if ansible_os_family == 'RedHat' else '/var/www/html/index.html' }}"
    owner: root
    group: root
    mode: '0644'

- name: Ensure Apache document root permissions
  file:
    path: "{{ '/var/www/html' }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes
  when: ansible_os_family == 'RedHat'

- name: Restart Apache to apply changes
  service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted

