- hosts: all
  become: true
  pre_tasks:

  - name: Update repository index / install updates on CentOS
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Update repository index / install updates on Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- name: Configure Ubuntu and CentOS servers
  hosts: all
  become: yes

  roles:
    - apache
    - prometheus_redhat
    - prometheus_ubuntu
    - motd
